---
- hosts: portainer
  vars:
    create_containers: 1
    default_container_name: portainer
    default_container_image: portainer/portainer-ce:latest
  
  tasks:
  - name: Update all installed packages using APT module
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
    register: apt_update_status

  - name: Remove packages not needed anymore
    apt:
      autoremove: yes

  - name: Install required system packages
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: latest
      update_cache: true

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
      update_cache: true

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Pull default docker image
    docker_image:
      name: "{{ default_container_image }}"
      source: pull

  - name: Create container
    docker_container:
      name: "{{ default_container_name }}{{ item }}"
      image: "{{ default_container_image }}"
      state: started
      ports: 9000:9000
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
    with_sequence: count={{ create_containers }}