---
- hosts: 10.209.65.125
  tasks:
    - name: Download Wazuh install script and execute with overwrite flag set
      ansible.builtin.shell: curl -sO https://packages.wazuh.com/4.3/wazuh-install.sh && sudo bash ./wazuh-install.sh -a -o
      become: true   # Ensure that the highest permissions are used on the remote host