---
- hosts: ubuntu
  tasks:
  - name: Install XCP-NG agent
    apt:
      name: 'xe-guest-utilities'
      state: latest
      update_cache: yes
      only_upgrade: yes
    ignore_errors: true
    ignore_unreachable: true
    register: apt_update_status

  - name: Reboot when packages were updated
    reboot:
      post_reboot_delay: 60
    throttle: 1
    ignore_errors: true
    ignore_unreachable: true
    when: apt_update_status.changed

- hosts: rhel
  tasks:
  - name: Add EPEL repository
    ansible.builtin.yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    ignore_errors: true
    ignore_unreachable: true
  
  - name: Update all installed packages using YUM module
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    ignore_errors: true
    ignore_unreachable: true
    register: yum_update_status
  
  - name: Update all installed packages using YUM module
    yum:
      name: 'xe-guest-utilities-latest'
      state: latest
      update_cache: yes
      update_only: yes
    ignore_errors: true
    ignore_unreachable: true
    register: yum_update_status
  
  - name: Enable service xe-linux-distribution and start it
    ansible.builtin.systemd:
      name: xe-linux-distribution
      enabled: yes
      state: started
    ignore_errors: true
    ignore_unreachable: true

  - name: Reboot when packages were updated
    reboot:
      post_reboot_delay: 60
    throttle: 1
    ignore_errors: true
    ignore_unreachable: true
    when: yum_update_status.changed